//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excellerent.EppConfiguration.Presentation.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Countries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Countries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excellerent.EppConfiguration.Presentation.Resource.Countries", typeof(Countries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{
        ///    &quot;error&quot;: false,
        ///    &quot;msg&quot;: &quot;countries and cities retrieved&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;iso2&quot;: &quot;AF&quot;,
        ///            &quot;iso3&quot;: &quot;AFG&quot;,
        ///            &quot;country&quot;: &quot;Afghanistan&quot;,
        ///            &quot;cities&quot;: [
        ///                &quot;Herat&quot;,
        ///                &quot;Kabul&quot;,
        ///                &quot;Kandahar&quot;,
        ///                &quot;Molah&quot;,
        ///                &quot;Rana&quot;,
        ///                &quot;Shar&quot;,
        ///                &quot;Sharif&quot;,
        ///                &quot;Wazir Akbar Khan&quot;
        ///            ]
        ///        },
        ///        {
        ///            &quot;iso2&quot;: &quot;AL&quot;,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countriesAndCities {
            get {
                return ResourceManager.GetString("countriesAndCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{
        ///    &quot;error&quot;: false,
        ///    &quot;msg&quot;: &quot;countries and codes retrieved&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;Afghanistan&quot;,
        ///            &quot;code&quot;: &quot;AF&quot;,
        ///            &quot;dial_code&quot;: &quot;+93&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;Albania&quot;,
        ///            &quot;code&quot;: &quot;AL&quot;,
        ///            &quot;dial_code&quot;: &quot;+355&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;Algeria&quot;,
        ///            &quot;code&quot;: &quot;DZ&quot;,
        ///            &quot;dial_code&quot;: &quot;+213&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;AmericanSamoa&quot;,
        ///            &quot;code&quot;: &quot;AS&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countriesAndCodes {
            get {
                return ResourceManager.GetString("countriesAndCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{
        ///    &quot;error&quot;: false,
        ///    &quot;msg&quot;: &quot;countries and states retrieved&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;Afghanistan&quot;,
        ///            &quot;iso3&quot;: &quot;AFG&quot;,
        ///            &quot;iso2&quot;: &quot;AF&quot;,
        ///            &quot;states&quot;: [
        ///                {
        ///                    &quot;name&quot;: &quot;Badakhshan&quot;,
        ///                    &quot;state_code&quot;: &quot;BDS&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;Badghis&quot;,
        ///                    &quot;state_code&quot;: &quot;BDG&quot;
        ///                },
        ///                {
        ///                    &quot;name&quot;: &quot;Baghlan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countriesAndStates {
            get {
                return ResourceManager.GetString("countriesAndStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{
        ///    &quot;error&quot;: false,
        ///    &quot;msg&quot;: &quot;countries and codes retrieved&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;Afghanistan&quot;,
        ///            &quot;code&quot;: &quot;AF&quot;,
        ///            &quot;dial_code&quot;: &quot;+93&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;Albania&quot;,
        ///            &quot;code&quot;: &quot;AL&quot;,
        ///            &quot;dial_code&quot;: &quot;+355&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;Algeria&quot;,
        ///            &quot;code&quot;: &quot;DZ&quot;,
        ///            &quot;dial_code&quot;: &quot;+213&quot;
        ///        },
        ///        {
        ///            &quot;name&quot;: &quot;AmericanSamoa&quot;,
        ///            &quot;code&quot;: &quot;AS&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countryAndCode {
            get {
                return ResourceManager.GetString("countryAndCode", resourceCulture);
            }
        }
    }
}
