//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excellerent.ReportManagement.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationEmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationEmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excellerent.ReportManagement.Core.Resource.NotificationEmailTemplate", typeof(NotificationEmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear &lt;b&gt;{userName}&lt;/b&gt;,
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    This is to inform you that your failure to submit your timesheet for the week of {Start} to {End}
        ///    which was due on {reminderDate}  has been escalated to your project supervisor(s). Please make sure you have
        ///    submitted your timesheet for the given week.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    To submit your timesheet now, go to
        ///    &lt;a href=&quot;{responseLink}&quot;&gt;Excellerent Projects Porfolio&lt;/a&gt;
        ///    and fill out the timesheet.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string FirstEscalationResourceNotification {
            get {
                return ResourceManager.GetString("FirstEscalationResourceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear &lt;b&gt;{userName}&lt;/b&gt;,&lt;/p&gt;
        ///&lt;p&gt;
        ///    This is to inform you that the following subordinates have not submitted
        ///    their timesheets for the week of {Start} to {End} which was due on {reminderDate}.
        ///&lt;/p&gt;
        ///&lt;ul&gt;
        ///    {employees}
        ///&lt;/ul&gt;
        ///&lt;p&gt;
        ///    You can verify that by going to &lt;a href=&quot;{responseLink}&quot;&gt;Excellerent Projects Porfolio&lt;/a&gt;.
        ///    Please see to them submitting their timesheets for the given week.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string FirstEscalationSupervisorNotification {
            get {
                return ResourceManager.GetString("FirstEscalationSupervisorNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear &lt;b&gt;{userName}&lt;/b&gt;,
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    This is a reminder that you have not submitted your timesheet for the week of {Start} to {End}.
        ///    Please complete and submit your timesheet before the end of business hours. Failure to submit 
        ///    your timesheets may result in late payments. If you have any questions please contact your supervisor.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    To submit your timesheet now, go to 
        ///    &lt;a href=&quot;{responseLink}&quot;&gt;Excellerent Projects Porfolio&lt;/a&gt;
        ///    and fill the timesheet.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ReminderResourceNotification {
            get {
                return ResourceManager.GetString("ReminderResourceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    This is to inform you that the following employees have not submitted their 
        ///    timesheets for the week of {Start} to {End} which was due on {reminderDate}. The employees are:
        ///&lt;/p&gt;
        ///&lt;ul&gt;
        ///    {employees}
        ///&lt;/ul&gt;
        ///&lt;p&gt;
        ///    Please see to them submitting their timesheets for the given week.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string SecondEscalationManagementNotification {
            get {
                return ResourceManager.GetString("SecondEscalationManagementNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    Dear &lt;b&gt;{userName}&lt;/b&gt;,
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    This is to inform you that your failure to submit your timesheet for the week of {Start} to {End}
        ///    which was due on {reminderDate} is escalated to HR. Please make sure you have submitted your timesheet for the given week.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    If you want to submit your timesheet first, please go to
        ///    &lt;a href=&quot;{responseLink}&quot;&gt;Excellerent Projects Porfolio&lt;/a&gt;.
        ///&lt;/p&gt;.
        /// </summary>
        internal static string SecondEscalationResourceNotification {
            get {
                return ResourceManager.GetString("SecondEscalationResourceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            padding: 10px;
        ///        }
        ///        th {
        ///            font-style: italic;
        ///            background: lightgray;
        ///        }
        ///        table {
        ///            align-self: center;
        ///            background: white;
        ///        }
        ///        td {
        ///            background: #f0f0f0;
        ///        }
        ///        th, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrapperGeneral {
            get {
                return ResourceManager.GetString("WrapperGeneral", resourceCulture);
            }
        }
    }
}
